---
resources:
- name: code
  type: git
  source:
    uri: https://github.com/aswin-apton/jenkines-test.git
    branch: master

jobs:
- name: unit
  plan:
  - get: code
    trigger: true
  - task: unit
    file: hello.py