---
resources:
- name: jenkines-test
  type: git
  source:
    uri: https://github.com/aswin-apton/jenkines-test
    branch: master

jobs:
- name: exec
  plan:
  - get: jenkines-test
    trigger: true
  - task: unit
    file: jenkines-test/ci/test1.yml