---
resources:
- name: jenkines-test
  type: git
  icon: github
  source:
    uri: https://github.com/aswin-apton/jenkines-test
    branch: master
    access_token: ((github-access-token))

jobs:
- name: test
  plan:
  - get: jenkines-test
    trigger: true
    version: every
    params:
      path: jenkines-test
  - task: unit-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: python, tag: "3.8.13-buster"}
      inputs:
        - name: jenkines-test
      run:
        path: python
        args:
        - python jenkines-test/input.py 3
        
        
